/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-09 03:56:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberModify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/ezen/Desktop/project6-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/book/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671504870577L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" \n");
      out.write("rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" \n");
      out.write("crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/92e616dfba.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<title>수정페이지</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/main.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body{\n");
      out.write("	margin : 0px 0px;\n");
      out.write("}\n");
      out.write(".pw_ok{\n");
      out.write("color:#008000;\n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pw_rewrite{\n");
      out.write("color:#ff0000; \n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pw_null{\n");
      out.write("color:#ff0000; \n");
      out.write("display: none;\n");
      out.write("}\n");
      out.write("#mem_pw::placeholder{\n");
      out.write("   font-size:8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(".pw_rewrite{\n");
      out.write("	width : 30px;\n");
      out.write("	height : 30px;\n");
      out.write("}\n");
      out.write(".fa-solid, .fas {\n");
      out.write("    font-weight: 900;\n");
      out.write("    margin: 0;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("	<form action=\"/mem/modify\" method=\"post\">		\n");
      out.write("		<input type=\"text\" name=\"mem_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden ><br>\n");
      out.write("		<table>\n");
      out.write("		<tr>\n");
      out.write("		<th>이름:</th>\n");
      out.write("		<td><input type=\"text\" name=\"mem_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly ></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("		<th>나이:</th>\n");
      out.write("		<td><input type=\"text\" name=\"mem_age\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly ></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("		<th>성별:</th>\n");
      out.write("		<td><input type=\"text\" name=\"mem_gender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly ></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("		<th>아이디:</th>\n");
      out.write("		<td><input type=\"text\" name=\"mem_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly ></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("		<th>비밀번호:</th>\n");
      out.write("		<td><input type=\"password\" name=\"mem_pw\" id=\"mem_pw\" onchange=\"checkPw()\" placeholder=\"비밀번호를 입력해주세요.\" required >\n");
      out.write("			<span class=\"pw_ok\"><i class=\"fa-solid fa-check\"></i></span>\n");
      out.write("                           <span class=\"pw_rewrite\"><i class=\"fa-solid fa-x\"></i></span>\n");
      out.write("                           <span class=\"pw_null\"><i class=\"fa-solid fa-x\"></i></span>\n");
      out.write("                           </td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("		<th>주소:</th>\n");
      out.write("		<td><input type=\"text\" name=\"mem_ad\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_ad}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("		<th>핸드폰번호:</th>\n");
      out.write("		<td><input type=\"text\" name=\"mem_cell_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_cell_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("		<th>선호카테고리:</th>\n");
      out.write("		<td><select name=\"mno_cno\">\n");
      out.write("			<option value=\"소설\">소설</option>\n");
      out.write("			<option value=\"에쎄이\">에쎼이</option>\n");
      out.write("			<option value=\"건강/취미\">건강/취미</option>\n");
      out.write("			<option value=\"컴퓨터/모바일\">컴퓨터/모바일</option>\n");
      out.write("			</select></td>\n");
      out.write("		</tr>\n");
      out.write("		</table>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<button type=\"submit\" class=\"btn btn-secondary\">수정하기!</button>\n");
      out.write("	</form>\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("	   function checkPw(){\n");
      out.write("		   var mem_pw = document.getElementById('mem_pw').value; //id값이 \"id\"인 입력란의 값을 저장\n");
      out.write("		   console.log(mem_pw);\n");
      out.write("		   $.ajax({\n");
      out.write("		      url:'/mem/pwCheck', //Controller에서 요청 받을 주소\n");
      out.write("		      type:'post', //POST 방식으로 전달\n");
      out.write("		      data:{mem_pw:mem_pw},\n");
      out.write("		      success:function(isOk){ //컨트롤러에서 넘어온 isOK값을 받는다 \n");
      out.write("		         if(isOk == 'pw_ok'){ //ok이면 가입 가능\n");
      out.write("		            $('.pw_ok').css(\"display\",\"inline-block\"); \n");
      out.write("		            $('.pw_rewrite').css(\"display\", \"none\"); //정규식 어긋나면\n");
      out.write("		            $('.pw_null').css(\"display\", \"none\");\n");
      out.write("		         }else if(isOk =='pw_null'){//input이 null값임. 입력 요청\n");
      out.write("		            $('.pw_ok').css(\"display\",\"none\"); \n");
      out.write("		            $('.pw_rewrite').css(\"display\", \"none\");\n");
      out.write("		            $('.pw_null').css(\"display\", \"inline-block\");\n");
      out.write("		         } \n");
      out.write("		         else { //중복일 경우\n");
      out.write("		            $('.pw_ok').css(\"display\", \"none\");\n");
      out.write("		            $('.pw_rewrite').css(\"display\",\"inline-block\");\n");
      out.write("		            $('.pw_null').css(\"display\", \"none\");\n");
      out.write("		            // alert(\"아이디를 다시 입력해주세요\");\n");
      out.write("		            $('#mem_pw').val('');\n");
      out.write("		         }\n");
      out.write("		      },\n");
      out.write("		      error:function(request,status,error){\n");
      out.write("		      console.log(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\n");
      out.write("		      }   \n");
      out.write("\n");
      out.write("		   });\n");
      out.write("		   };   \n");
      out.write("	</script>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
